version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      #The first bind mounts is the folder containing the script to seed our database
      - ./mongo/mongo-entrypoint:/docker-entrypoint-initdb.d
      #The two others are the json files to seed our database
      - ./mongo/lieux-de-tournage-a-paris.json:/lieux-de-tournage-a-paris.json
      #This is the volume to make the database persistent
      - location-db:/data/db
      #We connect the container to the bridge network
    networks:
      - cloud-project-network

  back:
    container_name: back
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - JWT_SECRET=Diane
    build:
      context: ./backend
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - cloud-project-network

  front:
    container_name: front
    build:
      context: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - back
    networks:
      - cloud-project-network


volumes:
  location-db:

networks:
  cloud-project-network:

